\Z
M
%

item20220202_paddy_ysb_dpm_crop
global_item_click_count	
defaultäÊğ¸ğ/ca
T
,

item"20211203_paddy_seed_treatment_crop
global_item_click_count	
default³äªüá/ca
T
,

item"20220202_sugarcane_fertilizer_crop
global_item_click_count	
defaultĞê“ãó/db
U
-

item#20220203_paddy_weed_management_crop
global_item_click_count	
defaultÜ›Ôİò/
ec
V
.

item$20220103_paddy_basal_fertilizer_crop
global_item_click_count	
defaultäÉ¨ïç/ec
V
.

item$20220203_pulses_weed_management_crop
global_item_click_count	
defaultô¶€ó/hf
Y
1

item'20220101_animal_goat_sheep_fm_livestock
global_item_click_count	
defaultÅ•ôã/hf
Y
1

item'20220103_pr_pulses_weed_management_crop
global_item_click_count	
defaultÇ•˜˜è/	hf
Y
1

item'20220201_animal_goat_sheep_fm_livestock
global_item_click_count	
defaultŒ’Şçî/
hf
Y
1

item'20220202_animal_goat_sheep_dm_livestock
global_item_click_count	
defaultğ¶òšñ/ig
Z
2

item(20211204_groundnut_sucking_pest_dpm_crop
global_item_click_count	
default«Â¹€â/jh
[
3

item)20220101_animal_chicken_duck_fm_livestock
global_item_click_count	
defaultÑ¿öã/
jh
[
3

item)20220102_animal_chicken_duck_pp_livestock
global_item_click_count	
defaultãÒÖ‘ç/jh
[
3

item)20220103_animal_chicken_duck_pp_livestock
global_item_click_count	
defaultÖ•“´é/	ki
\
4

item*20220101_pr_rabi_paddy_seed_treatment_crop
global_item_click_count	
default“õÀ†ã/lj
]
5

item+20220102_animal_cattle_buffalo_dm_livestock
global_item_click_count	
default³™Êûå/	nl
_
7

item-20220103_pr_paddy_zinc_application_basal_crop
global_item_click_count	
defaultãİÑ‚é/
nl
_
7

item-20220203_summer_wave_protection_measures_crop
global_item_click_count	
default°šÓ¸ò/vt
g
?

item520220101_pr_rabi_pulses_seed_treatment_pesticide_crop
global_item_click_count	
default¹ìíÜâ/vt
g
?

item520220103_pr_rabi_paddy_line_sowing_transplanting_crop
global_item_click_count	
default¢«–¿è/	wu
h
@

item620220101_paddy_broadcasting_fertilizer_management_crop
global_item_click_count	
default—âœã/xv
i
A

item720220101_pr_rabi_pulses_seeed_treatment_fungicides_crop
global_item_click_count	
default×¿ê°â/‰†
y
Q

itemG20220103_pr_rabi_pulses_seed_treatment_biofungicides_biofertilizer_crop
global_item_click_count	
defaultğÓÖÚè/