^\
O
'

item20220105_okra_fertilizer_crop
global_item_click_count	
default“úÕ£í/^\
O
'

item20220201_okra_fertilizer_crop
global_item_click_count	
default€¼ù™ï/b`
S
+

item!20220105_groundnut_tikka_dpm_crop
global_item_click_count	
defaultÒÜËùì/b`
S
+

item!20220202_groundnut_tikka_dpm_crop
global_item_click_count	
default†­Ù¸ó/ec
V
.

item$20220201_tomato_leaf_blight_dpm_crop
global_item_click_count	
default¹•¯”ï/ec
V
.

item$20220202_tomato_leaf_blight_dpm_crop
global_item_click_count	
defaultú²Á­ó/hf
Y
1

item'20211204_animal_goat_sheep_fm_livestock
global_item_click_count	
defaultŸ‚Ã©á/hf
Y
1

item'20220102_animal_goat_sheep_bm_livestock
global_item_click_count	
defaultæ—ïğæ/hf
Y
1

item'20220102_pr_pulses_weed_management_crop
global_item_click_count	
defaultÖ¨Ìæ/hf
Y
1

item'20220103_animal_goat_sheep_dm_livestock
global_item_click_count	
default·ªÕé/ig
Z
2

item(20220101_groundnut_sucking_pest_dpm_crop
global_item_click_count	
defaultÇãçĞä/ig
Z
2

item(20220201_groundnut_sucking_pest_dpm_crop
global_item_click_count	
defaultª¯¨ıî/ig
Z
2

item(20220201_paddy_fertilizer_tillering_crop
global_item_click_count	
defaultÀÃâğí/jh
[
3

item)20220105_animal_chicken_duck_dm_livestock
global_item_click_count	
defaultÌæµ²ì/jh
[
3

item)20220201_animal_chicken_duck_dm_livestock
global_item_click_count	
defaultÿŞ€šï/jh
[
3

item)20220202_blackgram_greengram_ipm_ymv_crop
global_item_click_count	
defaultè§Çğ/lj
]
5

item+20211204_animal_cattle_buffalo_dm_livestock
global_item_click_count	
default¡•Ìºá/	lj
]
5

item+20220101_animal_cattle_buffalo_fm_livestock
global_item_click_count	
defaultÇå³Éã/lj
]
5

item+20220103_animal_cattle_buffalo_pp_livestock
global_item_click_count	
defaultáÎ¡­é/lj
]
5

item+20220201_animal_cattle_buffalo_hm_livestock
global_item_click_count	
defaultÓæØÂî/lj
]
5

item+20220202_animal_cattle_buffalo_hm_livestock
global_item_click_count	
default›Ãòñ/nl
_
7

item-20220102_pr_paddy_zinc_application_basal_crop
global_item_click_count	
defaultéèÕËæ/nl
_
7

item-20220201_pulses_rabi_nutrient_management_crop
global_item_click_count	
defaultÚü€î/qo
b
:

item020220104_paddy_preemergence_weed_management_crop
global_item_click_count	
defaultôå§áë/qo
b
:

item020220104_pr_pulses_rabi_nutrient_management_crop
global_item_click_count	
default”Ã¸ë/
vt
g
?

item520220101_pr_rabi_paddy_line_sowing_transplanting_crop
global_item_click_count	
default¡ñöÖâ/vt
g
?

item520220102_pr_rabi_paddy_line_sowing_transplanting_crop
global_item_click_count	
default¦™Æÿä/wu
h
@

item620220105_animal_cattle_buffalo_goat_sheep_dm_livestock
global_item_click_count	
defaultèú¦ì/}
p
H

item>pr_rabi_pulses_seed_treatment_biofungicides_biofertilizer_crop
global_item_click_count	
default¶‹Òâá/‰†
y
Q

itemG20220102_pr_rabi_pulses_seed_treatment_biofungicides_biofertilizer_crop
global_item_click_count	
defaultßãİÍå/